import React from "react";

export const metadata = {
  title: "About Page",
  description:"generated by next app",
  openGraph: {
    title: 'About Us - My Company', 
    description: 'Learn more about our company and mission',
    images: ['/globe.svg'],
    url: 'http://localhost:3000/about',
  },
}

const AboutPage = () => {
  return <div>AboutPage</div>;
};

export default AboutPage;
