import React from 'react'

export const metadata = {
    title:{
        default: "Auth | Chai or Code",
        template: "%s | Chai or Code",
        absolute: "",
    },
    description: "Generated by Create next app"
}

const Login = () => {
  return (
    <div>Login</div>
  )
}

export default Login